# Generated by Django 6.0.6 on 2026-07-02 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0003_alter_produto_foto_imagemproduto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('ajuste_positivo', 'Ajuste Positivo'), ('ajuste_negativo', 'Ajuste Negativo'), ('inventario', 'Inventário'), ('transferencia', 'Transferência'), ('venda', 'Venda'), ('compra', 'Compra'), ('cancelamento_venda', 'Cancelamento de Venda'), ('cancelamento_compra', 'Cancelamento de Compra')], max_length=30)),
                ('quantidade', models.IntegerField()),
                ('saldo_anterior', models.IntegerField()),
                ('saldo_atual', models.IntegerField()),
                ('origem', models.CharField(blank=True, max_length=100, null=True)),
                ('local', models.CharField(default='Estoque Principal', max_length=100)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_movimentacao', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_estoque', to='produtos.produto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_estoque', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-data_movimentacao'],
            },
        ),
    ]
