# Generated by Django 6.0.6 on 2026-06-23 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('ajuste', 'Ajuste')], max_length=20)),
                ('motivo', models.CharField(choices=[('compra', 'Compra'), ('venda', 'Venda'), ('devolucao', 'Devolução'), ('troca', 'Troca'), ('avaria', 'Avaria'), ('inventario', 'Inventário'), ('outro', 'Outro')], max_length=20)),
                ('quantidade', models.IntegerField()),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_movimentacao', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-data_movimentacao'],
            },
        ),
    ]
