# Generated by Django 6.0.6 on 2026-07-03 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
        ('produtos', '0003_alter_produto_foto_imagemproduto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('em_andamento', 'Em andamento'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='em_andamento', max_length=20)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_finalizacao', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventarios_estoque', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inventário',
                'verbose_name_plural': 'Inventários',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='InventarioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estoque_sistema', models.IntegerField()),
                ('quantidade_fisica', models.IntegerField(blank=True, null=True)),
                ('diferenca', models.IntegerField(default=0)),
                ('ajustado', models.BooleanField(default=False)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='estoque.inventario')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_inventario', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Item de Inventário',
                'verbose_name_plural': 'Itens de Inventário',
                'ordering': ['produto__modelo'],
            },
        ),
    ]
