# Generated by Django 6.0.6 on 2026-08-05 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_inventario_inventarioitem'),
        ('produtos', '0008_campos_opcionais_produto_variacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='variacao_cor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_estoque', to='produtos.variacaocor'),
        ),
    ]
