# Generated by Django 6.0.6 on 2026-08-09 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_movimentacaoestoque_variacao_cor'),
        ('produtos', '0009_produto_categoria_comercial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventarioitem',
            name='variacao_cor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_inventario', to='produtos.variacaocor', verbose_name='Cor / Variação'),
        ),
    ]
