# Generated by Django 6.0.6 on 2026-08-24 16:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financeiro', '0004_contareceber_historicocontareceber_parcelareceber_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160, verbose_name='Nome do evento')),
                ('status', models.CharField(choices=[('planejado', 'Planejado'), ('confirmado', 'Confirmado'), ('preparacao', 'Em preparação'), ('andamento', 'Em andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='planejado', max_length=20)),
                ('inicio', models.DateTimeField(verbose_name='Início')),
                ('fim', models.DateTimeField(verbose_name='Término')),
                ('local', models.CharField(blank=True, max_length=160)),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=2)),
                ('publico_alvo', models.CharField(blank=True, max_length=160, verbose_name='Público-alvo')),
                ('expectativa_publico', models.PositiveIntegerField(blank=True, null=True, verbose_name='Expectativa de público')),
                ('contato_responsavel', models.CharField(blank=True, max_length=30, verbose_name='Contato do responsável')),
                ('participantes_externos', models.TextField(blank=True, help_text='Informe um nome por linha quando a pessoa ainda não for usuária do ERP.', verbose_name='Outros participantes')),
                ('organizador', models.CharField(blank=True, max_length=160)),
                ('contato_organizador', models.CharField(blank=True, max_length=100, verbose_name='Contato do organizador')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_criados', to=settings.AUTH_USER_MODEL)),
                ('participantes', models.ManyToManyField(blank=True, related_name='eventos_participados', to=settings.AUTH_USER_MODEL)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_responsaveis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['inicio', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='DespesaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrado_em', models.DateTimeField(auto_now_add=True)),
                ('conta_pagar', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='despesa_evento', to='financeiro.contapagar')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='eventos.evento')),
            ],
            options={
                'ordering': ['-registrado_em'],
            },
        ),
        migrations.CreateModel(
            name='VendaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.localdate)),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição ou cliente')),
                ('valor_venda', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('custo_produtos', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('valor_recebido', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('forma_recebimento', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('parcial', 'Parcialmente recebida'), ('recebida', 'Recebida'), ('cancelada', 'Cancelada')], default='pendente', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('registrado_em', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendas', to='eventos.evento')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data', '-registrado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['inicio', 'status'], name='evento_inicio_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='evento',
            constraint=models.CheckConstraint(condition=models.Q(('fim__gte', models.F('inicio'))), name='evento_fim_apos_inicio'),
        ),
        migrations.AddConstraint(
            model_name='vendaevento',
            constraint=models.CheckConstraint(condition=models.Q(('valor_venda__gt', 0)), name='evento_venda_valor_positivo'),
        ),
        migrations.AddConstraint(
            model_name='vendaevento',
            constraint=models.CheckConstraint(condition=models.Q(('custo_produtos__gte', 0)), name='evento_venda_custo_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='vendaevento',
            constraint=models.CheckConstraint(condition=models.Q(('valor_recebido__gte', 0), ('valor_recebido__lte', models.F('valor_venda'))), name='evento_venda_recebido_valido'),
        ),
    ]
