# Generated by Django 6.0.6 on 2026-08-24 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_categorias_iniciais'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProdutoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de produto da Use Helvi',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='instagram',
            field=models.CharField(blank=True, max_length=80, verbose_name='Instagram do evento/organizador'),
        ),
        migrations.AddField(
            model_name='evento',
            name='tipo_contato_responsavel',
            field=models.CharField(blank=True, choices=[('whatsapp', 'WhatsApp'), ('telefone', 'Telefone'), ('email', 'E-mail')], default='whatsapp', max_length=12, verbose_name='Tipo de contato'),
        ),
        migrations.AddField(
            model_name='vendaevento',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='despesaevento',
            name='evento',
            field=models.ForeignKey(blank=True, help_text='Deixe vazio para uma despesa geral da Use Helvi.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='eventos.evento'),
        ),
        migrations.AddField(
            model_name='vendaevento',
            name='tipo_produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='eventos.tipoprodutoevento', verbose_name='Tipo de produto'),
        ),
    ]
