# Generated by Django 6.0.6 on 2026-08-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_cadastros_iniciais_use_helvi'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='tipo_contato_organizador',
            field=models.CharField(blank=True, choices=[('whatsapp', 'WhatsApp'), ('telefone', 'Telefone'), ('email', 'E-mail')], default='whatsapp', max_length=12, verbose_name='Tipo de contato do organizador'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='contato_responsavel',
            field=models.CharField(blank=True, max_length=120, verbose_name='Contato do responsável'),
        ),
    ]
