# Generated by Django 6.0.6 on 2026-08-24 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_evento_cancelado_em_evento_cancelado_por_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipeEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='equipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='eventos.equipeevento', verbose_name='Equipe cadastrada'),
        ),
        migrations.CreateModel(
            name='PessoaEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('tipo_contato', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('telefone', 'Telefone'), ('email', 'E-mail')], default='whatsapp', max_length=12)),
                ('contato', models.CharField(blank=True, max_length=120)),
                ('instagram', models.CharField(blank=True, max_length=80)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nome'],
                'constraints': [models.UniqueConstraint(fields=('nome', 'contato'), name='evento_pessoa_nome_contato_unicos')],
            },
        ),
        migrations.AddField(
            model_name='equipeevento',
            name='pessoas',
            field=models.ManyToManyField(blank=True, related_name='equipes', to='eventos.pessoaequipe'),
        ),
        migrations.AddField(
            model_name='evento',
            name='pessoas_equipe',
            field=models.ManyToManyField(blank=True, related_name='eventos', to='eventos.pessoaequipe', verbose_name='Pessoas cadastradas'),
        ),
    ]
