# Generated by Django 6.0.6 on 2026-08-24 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0008_categoria_outros_remove_compras_homologacao'),
        ('financeiro', '0005_contafinanceira_operacao_contapagar_operacao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceitaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrado_em', models.DateTimeField(auto_now_add=True)),
                ('conta_receber', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receita_evento', to='financeiro.contareceber')),
                ('evento', models.ForeignKey(blank=True, help_text='Deixe vazio para uma receita geral da Use Helvi.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receitas', to='eventos.evento')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-registrado_em'],
            },
        ),
    ]
