# Generated by Django 6.0.6 on 2026-08-25 21:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0012_remove_instagram_pessoa_e_ajusta_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoaequipe',
            name='cor_agenda',
            field=models.CharField(default='#B76E79', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Informe uma cor válida.')], verbose_name='Cor na agenda'),
        ),
    ]
