# Generated by Django 6.0.6 on 2026-08-25 21:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0013_alter_pessoaequipe_cor_agenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoaequipe',
            name='cor_agenda',
            field=models.CharField(default='#D84A8B', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Informe uma cor válida.')], verbose_name='Cor na agenda'),
        ),
    ]
