# Generated by Django 6.0.6 on 2026-08-26 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0014_alter_pessoaequipe_cor_agenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='participante_principal',
            field=models.ForeignKey(blank=True, help_text='A cor desta pessoa identifica o evento na agenda.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_como_principal', to='eventos.pessoaequipe', verbose_name='Participante principal'),
        ),
    ]
