# Generated by Django 6.0.6 on 2026-08-26 03:01

from django.db import migrations, models


def copiar_participante_principal(apps, schema_editor):
    Evento = apps.get_model('eventos', 'Evento')
    for evento in Evento.objects.exclude(participante_principal_id=None).iterator():
        evento.participantes_destaque.add(evento.participante_principal_id)


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0015_evento_participante_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='participantes_destaque',
            field=models.ManyToManyField(blank=True, help_text='As cores selecionadas aparecem juntas no cartão do evento.', related_name='eventos_em_destaque', to='eventos.pessoaequipe', verbose_name='Participantes em destaque na Agenda'),
        ),
        migrations.RunPython(copiar_participante_principal, migrations.RunPython.noop),
    ]
