services:
  - type: web
    name: erp-helvi-homologacao
    runtime: docker
    plan: free
    branch: homologacao
    autoDeployTrigger: commit
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /senha/login/
    envVars:
      - key: APP_ENV
        value: staging
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DB_ENGINE
        value: postgresql
      - key: DB_NAME
        value: postgres
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "5432"
      - key: DB_SSLMODE
        value: require
      - key: ALLOWED_HOSTS
        value: erp-helvi-homologacao.onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://erp-helvi-homologacao.onrender.com
      - key: SECURE_SSL_REDIRECT
        value: "True"
      - key: SESSION_COOKIE_SECURE
        value: "True"
      - key: CSRF_COOKIE_SECURE
        value: "True"
      - key: SECURE_HSTS_SECONDS
        value: "31536000"
      - key: SECURE_HSTS_INCLUDE_SUBDOMAINS
        value: "True"
      - key: SECURE_HSTS_PRELOAD
        value: "False"
      - key: SUPABASE_STORAGE_ENABLED
        value: "True"
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SECRET_KEY
        sync: false
      - key: SUPABASE_STORAGE_BUCKET
        value: erp-helvi-media
      - key: SUPABASE_STORAGE_URL_EXPIRE
        value: "3600"
      - key: EMAIL_BACKEND
        value: django.core.mail.backends.console.EmailBackend
      - key: LOG_LEVEL
        value: INFO
