# Generated by Django 6.0.6 on 2026-06-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_marca_data_atualizacao_alter_marca_ativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colecao',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='colecao',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='colecao',
            name='nome',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome'),
        ),
    ]
