# Generated by Django 6.0.6 on 2026-08-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton', models.BooleanField(default=True, editable=False, unique=True)),
                ('nome_fantasia', models.CharField(max_length=150, verbose_name='Nome fantasia')),
                ('razao_social', models.CharField(max_length=200, verbose_name='Razão social')),
                ('cnpj', models.CharField(blank=True, max_length=18, verbose_name='CNPJ')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=30, verbose_name='Inscrição estadual')),
                ('inscricao_municipal', models.CharField(blank=True, max_length=30, verbose_name='Inscrição municipal')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('site', models.URLField(blank=True, verbose_name='Site')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, max_length=180, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=20, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='Estado')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresa/', verbose_name='Logo institucional')),
                ('rodape_documentos', models.TextField(blank=True, help_text='Texto exibido no rodapé de orçamentos, vendas, comprovantes e relatórios.', verbose_name='Rodapé dos documentos')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Dados da empresa',
                'verbose_name_plural': 'Dados da empresa',
            },
        ),
    ]
