# Generated by Django 6.0.6 on 2026-06-23 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(max_length=100)),
                ('cor', models.CharField(blank=True, max_length=80, null=True)),
                ('material', models.CharField(blank=True, max_length=100, null=True)),
                ('genero', models.CharField(choices=[('unissex', 'Unissex'), ('masculino', 'Masculino'), ('feminino', 'Feminino'), ('infantil', 'Infantil')], default='unissex', max_length=20)),
                ('preco_custo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('preco_venda', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estoque_atual', models.IntegerField(default=0)),
                ('estoque_minimo', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Produto / Armação',
                'verbose_name_plural': 'Produtos / Armações',
            },
        ),
    ]
