# Generated by Django 6.0.6 on 2026-06-26 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['modelo'], 'verbose_name': 'Produto / Armação', 'verbose_name_plural': 'Produtos / Armações'},
        ),
        migrations.RemoveField(
            model_name='produto',
            name='cor',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='material',
        ),
        migrations.AddField(
            model_name='produto',
            name='colecao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='catalogo.colecao', verbose_name='Coleção'),
        ),
        migrations.AddField(
            model_name='produto',
            name='cores_disponiveis',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Cores Disponíveis'),
        ),
        migrations.AddField(
            model_name='produto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/'),
        ),
        migrations.AddField(
            model_name='produto',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='produto',
            name='tipo_armacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='catalogo.tipoarmacao', verbose_name='Tipo de Armação'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='estoque_atual',
            field=models.IntegerField(default=0, verbose_name='Estoque Atual'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='estoque_minimo',
            field=models.IntegerField(default=0, verbose_name='Estoque Mínimo'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='genero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='catalogo.genero', verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='catalogo.marca'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_custo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço de Custo'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_venda',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço de Venda'),
        ),
    ]
