# Generated by Django 6.0.6 on 2026-07-15 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0001_initial'),
        ('produtos', '0003_alter_produto_foto_imagemproduto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='codigo_fornecedor',
            field=models.CharField(blank=True, max_length=80, verbose_name='Código do fornecedor'),
        ),
        migrations.AddField(
            model_name='produto',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='fornecedores.fornecedor', verbose_name='Fornecedor principal'),
        ),
    ]
