# Generated by Django 6.0.6 on 2026-07-15 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_produto_codigo_fornecedor_produto_fornecedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='fornecedor',
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo_fornecedor',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Código do fornecedor'),
        ),
    ]
