# Generated by Django 6.0.6 on 2026-08-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_campos_opcionais_produto_variacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria_comercial',
            field=models.CharField(choices=[('armacao', 'Armação'), ('acessorio', 'Acessório')], default='armacao', max_length=20, verbose_name='Categoria Comercial'),
        ),
    ]
