# Generated by Django 6.0.6 on 2026-08-12 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0012_itemimportacaocatalogo_arquivo_principal'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecorteImportacaoCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('hero', 'Hero'), ('variacao', 'Variação')], max_length=20)),
                ('indice', models.PositiveIntegerField(default=0)),
                ('imagem', models.ImageField(upload_to='importacoes_catalogo/recortes/%Y/%m/')),
                ('nome_cor', models.CharField(blank=True, max_length=100)),
                ('cor_hex', models.CharField(default='#6c757d', max_length=7)),
                ('texto_hex', models.CharField(default='#ffffff', max_length=7)),
                ('layout', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('arquivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recortes', to='produtos.arquivoimportacaocatalogo')),
            ],
            options={
                'ordering': ['tipo', 'indice', 'id'],
                'constraints': [models.UniqueConstraint(fields=('arquivo', 'tipo', 'indice'), name='recorte_catalogo_arquivo_tipo_indice_unico')],
            },
        ),
    ]
