# Generated by Django 6.0.6 on 2026-06-24 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='estoque_baixado',
            field=models.BooleanField(default=False),
        ),
    ]
