# Generated by Django 6.0.6 on 2026-07-22 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0002_orcamento_cliente_documento_orcamento_cliente_email_and_more'),
        ('vendas', '0002_venda_estoque_baixado'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='orcamento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='venda', to='comercial.orcamento'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('pix', 'Pix'), ('dinheiro', 'Dinheiro'), ('cartao', 'Cartão'), ('boleto', 'Boleto'), ('prazo', 'A prazo')], max_length=20, null=True),
        ),
    ]
