# Generated by Django 6.0.6 on 2026-07-22 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_venda_orcamento_alter_venda_forma_pagamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='orcamento',
        ),
    ]
