# Generated by Django 6.0.6 on 2026-07-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0006_normalizar_vendas_existentes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenciaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('venda', 'Venda'), ('compra', 'Compra'), ('orcamento', 'Orçamento')], max_length=30, unique=True, verbose_name='Tipo de documento')),
                ('ultimo_numero', models.PositiveIntegerField(default=0, verbose_name='Último número utilizado')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Sequência de documento',
                'verbose_name_plural': 'Sequências de documentos',
                'ordering': ['tipo'],
            },
        ),
    ]
