# Generated by Django 6.0.6 on 2026-07-23 03:38

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_contareceber_historicocontareceber_parcelareceber_and_more'),
        ('vendas', '0008_alter_venda_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='conta_financeira',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='financeiro.contafinanceira'),
        ),
        migrations.AddField(
            model_name='venda',
            name='primeiro_vencimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='quantidade_parcelas',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='venda',
            name='valor_entrada',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='venda',
            name='valor_troco',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='venda',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('pix', 'Pix'), ('dinheiro', 'Dinheiro'), ('cartao_debito', 'Cartão de Débito'), ('cartao_credito', 'Cartão de Crédito'), ('transferencia', 'Transferência'), ('boleto', 'Boleto'), ('prazo', 'A Prazo')], max_length=20, null=True),
        ),
    ]
