# Generated by Django 6.0.6 on 2026-08-05 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_campos_opcionais_produto_variacao'),
        ('vendas', '0010_venda_regras_monetarias'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='itemvenda',
            name='venda_produto_unico',
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='variacao_cor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_venda', to='produtos.variacaocor'),
        ),
        migrations.AddField(
            model_name='venda',
            name='entrega_bairro',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='venda',
            name='entrega_cep',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='venda',
            name='entrega_cidade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='venda',
            name='entrega_complemento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='venda',
            name='entrega_estado',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='venda',
            name='entrega_logradouro',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='venda',
            name='entrega_numero',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='venda',
            name='tipo_entrega',
            field=models.CharField(choices=[('retirada', 'Retirada'), ('envio', 'Envio / entrega')], default='retirada', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='itemvenda',
            constraint=models.UniqueConstraint(fields=('venda', 'produto', 'variacao_cor'), name='venda_produto_cor_unico'),
        ),
    ]
