# Generated by Django 6.0.6 on 2026-07-01 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(choices=[('ADM', 'Administrador'), ('GER', 'Gerente'), ('VEN', 'Vendedor'), ('FIN', 'Financeiro')], default='VEN', max_length=3, verbose_name='Perfil'),
        ),
    ]
