"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

ENV_FILE = Path(os.getenv("DJANGO_ENV_FILE", BASE_DIR / ".env"))
if not ENV_FILE.is_absolute():
    ENV_FILE = BASE_DIR / ENV_FILE
load_dotenv(ENV_FILE)

APP_ENV = os.getenv("APP_ENV", "development").strip().lower()
AMBIENTES_VALIDOS = {"development", "staging", "production"}
if APP_ENV not in AMBIENTES_VALIDOS:
    raise ImproperlyConfigured(
        "APP_ENV deve ser development, staging ou production."
    )


def env_bool(nome, padrao=False):
    valor_padrao = "True" if padrao else "False"
    return os.getenv(nome, valor_padrao).strip().lower() in {
        "1",
        "true",
        "yes",
        "on",
    }


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DEBUG", False)

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")

CSRF_TRUSTED_ORIGINS = os.getenv(
    "CSRF_TRUSTED_ORIGINS",
    "http://localhost:8000,http://127.0.0.1:8000"
).split(",")

CSRF_FAILURE_VIEW = "core.security.csrf_failure"


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',

    'core',
    'catalogo',
    'usuarios.apps.UsuariosConfig',
    'clientes',
    'fornecedores',
    'produtos',
    'estoque',
    'vendas',
    'financeiro.apps.FinanceiroConfig',
    'configuracoes',
    'compras',
    "comercial.apps.ComercialConfig",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'usuarios.middleware.PermissaoModuloMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'core/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                "usuarios.context_processors.permissoes_usuario",
                "core.context_processors.ambiente_aplicacao",
                "core.context_processors.operacao_ativa",
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

#DATABASES = {
#    "default": {
#        "ENGINE": "django.db.backends.postgresql",
#        "NAME": os.getenv("DB_NAME"),
#        "USER": os.getenv("DB_USER"),
#        "PASSWORD": os.getenv("DB_PASSWORD"),
#        "HOST": os.getenv("DB_HOST"),
#        "PORT": os.getenv("DB_PORT", "5432"),
#        "OPTIONS": {
#            "sslmode": os.getenv("DB_SSLMODE", "prefer"),
#        },
#    }
#}
DB_ENGINE = os.getenv("DB_ENGINE", "sqlite").lower()

if DB_ENGINE == "postgresql":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("DB_NAME"),
            "USER": os.getenv("DB_USER"),
            "PASSWORD": os.getenv("DB_PASSWORD"),
            "HOST": os.getenv("DB_HOST"),
            "PORT": os.getenv("DB_PORT", "5432"),
            "OPTIONS": {
                "sslmode": os.getenv("DB_SSLMODE", "prefer"),
            },
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

STATIC_ROOT = BASE_DIR / "staticfiles"

SUPABASE_STORAGE_ENABLED = env_bool("SUPABASE_STORAGE_ENABLED", False)

SUPABASE_STORAGE_BUCKET = os.getenv("SUPABASE_STORAGE_BUCKET", "").strip()
SUPABASE_STORAGE_ENDPOINT = os.getenv("SUPABASE_STORAGE_ENDPOINT", "").strip()
SUPABASE_STORAGE_REGION = os.getenv("SUPABASE_STORAGE_REGION", "").strip()
SUPABASE_STORAGE_ACCESS_KEY_ID = os.getenv("SUPABASE_STORAGE_ACCESS_KEY_ID", "").strip()
SUPABASE_STORAGE_SECRET_ACCESS_KEY = os.getenv("SUPABASE_STORAGE_SECRET_ACCESS_KEY", "").strip()
SUPABASE_STORAGE_URL_EXPIRE = int(os.getenv("SUPABASE_STORAGE_URL_EXPIRE", "3600"))

if SUPABASE_STORAGE_ENABLED:
    obrigatorias_storage = {
        "SUPABASE_STORAGE_BUCKET": SUPABASE_STORAGE_BUCKET,
        "SUPABASE_STORAGE_ENDPOINT": SUPABASE_STORAGE_ENDPOINT,
        "SUPABASE_STORAGE_REGION": SUPABASE_STORAGE_REGION,
        "SUPABASE_STORAGE_ACCESS_KEY_ID": SUPABASE_STORAGE_ACCESS_KEY_ID,
        "SUPABASE_STORAGE_SECRET_ACCESS_KEY": SUPABASE_STORAGE_SECRET_ACCESS_KEY,
    }
    ausentes_storage = [nome for nome, valor in obrigatorias_storage.items() if not valor]
    if ausentes_storage:
        raise ImproperlyConfigured(
            "Supabase Storage habilitado, mas faltam variáveis: "
            + ", ".join(ausentes_storage)
        )

    default_storage = {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "access_key": SUPABASE_STORAGE_ACCESS_KEY_ID,
            "secret_key": SUPABASE_STORAGE_SECRET_ACCESS_KEY,
            "bucket_name": SUPABASE_STORAGE_BUCKET,
            "endpoint_url": SUPABASE_STORAGE_ENDPOINT,
            "region_name": SUPABASE_STORAGE_REGION,
            # Supabase exige forcePathStyle=true nos clientes S3.
            "addressing_style": "path",
            "signature_version": "s3v4",
            # O bucket do ERP é privado; .url gera URL assinada temporária.
            "querystring_auth": True,
            "querystring_expire": SUPABASE_STORAGE_URL_EXPIRE,
            "default_acl": None,
            # Não sobrescrever uploads com o mesmo nome.
            "file_overwrite": False,
        },
    }
else:
    default_storage = {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    }

STORAGES = {
    "default": default_storage,
    "staticfiles": {
        "BACKEND": (
            "django.contrib.staticfiles.storage.StaticFilesStorage"
            if DEBUG
            else "whitenoise.storage.CompressedManifestStaticFilesStorage"
        ),
    },
}

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'selecionar_operacao'
LOGOUT_REDIRECT_URL = 'login'

# Sessão expira após 30 minutos sem atividade.
SESSION_COOKIE_AGE = int(
    os.getenv("SESSION_COOKIE_AGE", "1800")
)

# Renova o prazo a cada requisição realizada pelo usuário.
SESSION_SAVE_EVERY_REQUEST = True

# Encerra a sessão também quando o navegador é fechado.
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Proteção contra tentativas repetidas de autenticação.
LOGIN_MAX_TENTATIVAS = int(os.getenv("LOGIN_MAX_TENTATIVAS", "5"))
LOGIN_BLOQUEIO_SEGUNDOS = int(os.getenv("LOGIN_BLOQUEIO_SEGUNDOS", "900"))

AUTH_USER_MODEL = "usuarios.Usuario"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend",
)
if APP_ENV == "staging":
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
EMAIL_HOST = os.getenv("EMAIL_HOST", "")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = env_bool("EMAIL_USE_TLS", True)
EMAIL_USE_SSL = env_bool("EMAIL_USE_SSL", False)
DEFAULT_FROM_EMAIL = os.getenv(
    "DEFAULT_FROM_EMAIL",
    "ERP Helvi <nao-responda@helvi.local>",
)

# Segurança de implantação. Em desenvolvimento local, os padrões permanecem
# compatíveis com HTTP; com DEBUG=False, HTTPS e cookies seguros são exigidos.
SECURE_SSL_REDIRECT = env_bool("SECURE_SSL_REDIRECT", not DEBUG)
SESSION_COOKIE_SECURE = env_bool("SESSION_COOKIE_SECURE", not DEBUG)
CSRF_COOKIE_SECURE = env_bool("CSRF_COOKIE_SECURE", not DEBUG)
SECURE_HSTS_SECONDS = int(
    os.getenv(
        "SECURE_HSTS_SECONDS",
        "31536000" if not DEBUG else "0",
    )
)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool(
    "SECURE_HSTS_INCLUDE_SUBDOMAINS",
    not DEBUG,
)
SECURE_HSTS_PRELOAD = env_bool("SECURE_HSTS_PRELOAD", not DEBUG)
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
X_FRAME_OPTIONS = "DENY"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": os.getenv("LOG_LEVEL", "INFO"),
    },
}
