# Generated by Django 6.0.6 on 2026-07-21 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('comercial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='cliente_documento',
            field=models.CharField(blank=True, max_length=18, verbose_name='CPF / CNPJ'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='cliente_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='cliente_nome',
            field=models.CharField(default='', max_length=150, verbose_name='Cliente / interessado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orcamento',
            name='cliente_telefone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone / WhatsApp'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos', to='clientes.cliente', verbose_name='Cliente cadastrado'),
        ),
    ]
