# Generated by Django 6.0.6 on 2026-08-03 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0002_orcamento_cliente_documento_orcamento_cliente_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompartilhamentoOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'E-mail')], max_length=20, verbose_name='Canal')),
                ('destinatario', models.CharField(max_length=254, verbose_name='Destinatário')),
                ('assunto', models.CharField(blank=True, max_length=200, verbose_name='Assunto')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('resultado', models.CharField(choices=[('preparado', 'Preparado'), ('enviado', 'Enviado'), ('falha', 'Falha')], max_length=20, verbose_name='Resultado')),
                ('detalhe', models.TextField(blank=True, verbose_name='Detalhe')),
                ('realizado_em', models.DateTimeField(auto_now_add=True, verbose_name='Realizado em')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compartilhamentos', to='comercial.orcamento', verbose_name='Orçamento')),
                ('realizado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compartilhamentos_orcamento', to=settings.AUTH_USER_MODEL, verbose_name='Realizado por')),
            ],
            options={
                'verbose_name': 'Compartilhamento de orçamento',
                'verbose_name_plural': 'Compartilhamentos de orçamento',
                'ordering': ['-realizado_em', '-pk'],
                'indexes': [models.Index(fields=['orcamento', 'canal'], name='orc_comp_canal_idx'), models.Index(fields=['realizado_em'], name='orc_comp_data_idx')],
            },
        ),
    ]
