# Generated by Django 6.0.6 on 2026-08-05 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0003_compartilhamentoorcamento'),
        ('produtos', '0008_campos_opcionais_produto_variacao'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='itemorcamento',
            name='orcamento_produto_unico',
        ),
        migrations.AddField(
            model_name='itemorcamento',
            name='variacao_cor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_orcamento', to='produtos.variacaocor', verbose_name='Variação de cor'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='entrega_bairro',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='entrega_cep',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='entrega_cidade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='entrega_complemento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='entrega_estado',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='entrega_logradouro',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='entrega_numero',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='tipo_entrega',
            field=models.CharField(choices=[('retirada', 'Retirada'), ('envio', 'Envio / entrega')], default='retirada', max_length=10, verbose_name='Forma de entrega'),
        ),
        migrations.AddConstraint(
            model_name='itemorcamento',
            constraint=models.UniqueConstraint(fields=('orcamento', 'produto', 'variacao_cor'), name='orcamento_produto_cor_unico'),
        ),
    ]
