# Generated by Django 6.0.6 on 2026-07-15 16:24

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0006_compra_fornecedor'),
        ('fornecedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativa')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('caixa', 'Caixa'), ('conta_bancaria', 'Conta bancária'), ('carteira_digital', 'Carteira digital'), ('adquirente', 'Adquirente'), ('outra', 'Outra')], default='conta_bancaria', max_length=30, verbose_name='Tipo')),
                ('instituicao', models.CharField(blank=True, max_length=100, verbose_name='Instituição')),
                ('agencia', models.CharField(blank=True, max_length=20, verbose_name='Agência')),
                ('numero_conta', models.CharField(blank=True, max_length=30, verbose_name='Número da conta')),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Saldo inicial')),
                ('data_saldo_inicial', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data do saldo inicial')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Conta financeira',
                'verbose_name_plural': 'Contas financeiras',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('tipo', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], default='despesa', max_length=10, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Categoria financeira',
                'verbose_name_plural': 'Categorias financeiras',
                'ordering': ['tipo', 'nome'],
                'constraints': [models.UniqueConstraint(fields=('nome', 'tipo'), name='financeiro_categoria_nome_tipo_unicos')],
            },
        ),
        migrations.CreateModel(
            name='BaixaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data do pagamento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor principal')),
                ('juros', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Juros')),
                ('multa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Multa')),
                ('desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Desconto financeiro')),
                ('valor_movimentado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor movimentado')),
                ('forma_pagamento', models.CharField(choices=[('pix', 'Pix'), ('dinheiro', 'Dinheiro'), ('cartao', 'Cartão'), ('boleto', 'Boleto'), ('transferencia', 'Transferência'), ('outra', 'Outra')], default='pix', max_length=30, verbose_name='Forma de pagamento')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('registrado_em', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('estornada', models.BooleanField(default=False, verbose_name='Estornada')),
                ('estornada_em', models.DateTimeField(blank=True, null=True, verbose_name='Estornada em')),
                ('motivo_estorno', models.TextField(blank=True, verbose_name='Motivo do estorno')),
                ('estornada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='baixas_pagar_estornadas', to=settings.AUTH_USER_MODEL, verbose_name='Estornada por')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='baixas_pagar_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('conta_financeira', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='baixas_pagar', to='financeiro.contafinanceira', verbose_name='Conta financeira')),
            ],
            options={
                'verbose_name': 'Baixa de conta a pagar',
                'verbose_name_plural': 'Baixas de contas a pagar',
                'ordering': ['-data_pagamento', '-registrado_em'],
            },
        ),
        migrations.CreateModel(
            name='ContaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(editable=False, unique=True, verbose_name='Número')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('data_emissao', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data de emissão')),
                ('data_competencia', models.DateField(blank=True, null=True, verbose_name='Data de competência')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor total')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor pago')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('parcial', 'Parcial'), ('paga', 'Paga'), ('cancelada', 'Cancelada')], default='pendente', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cancelado_em', models.DateTimeField(blank=True, null=True, verbose_name='Cancelado em')),
                ('motivo_cancelamento', models.TextField(blank=True, verbose_name='Motivo do cancelamento')),
                ('cancelado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_pagar_canceladas', to=settings.AUTH_USER_MODEL, verbose_name='Cancelado por')),
                ('categoria', models.ForeignKey(limit_choices_to={'tipo': 'despesa'}, on_delete=django.db.models.deletion.PROTECT, related_name='contas_pagar', to='financeiro.categoriafinanceira', verbose_name='Categoria')),
                ('compra', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conta_pagar', to='compras.compra', verbose_name='Compra de origem')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_pagar_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_pagar', to='fornecedores.fornecedor', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Conta a pagar',
                'verbose_name_plural': 'Contas a pagar',
                'ordering': ['-data_emissao', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoContaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('criacao', 'Criação'), ('edicao', 'Edição'), ('parcela_criada', 'Parcela criada'), ('parcela_editada', 'Parcela editada'), ('baixa', 'Baixa registrada'), ('estorno', 'Baixa estornada'), ('cancelamento', 'Cancelamento'), ('reativacao', 'Reativação'), ('integracao_compra', 'Integração com compra'), ('outro', 'Outro')], max_length=30, verbose_name='Tipo de evento')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('dados', models.JSONField(blank=True, default=dict, verbose_name='Dados do evento')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('conta_pagar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='financeiro.contapagar', verbose_name='Conta a pagar')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historicos_contas_pagar', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Histórico da conta a pagar',
                'verbose_name_plural': 'Históricos das contas a pagar',
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('estorno_entrada', 'Estorno de entrada'), ('estorno_saida', 'Estorno de saída'), ('ajuste', 'Ajuste')], max_length=30, verbose_name='Tipo')),
                ('data_movimentacao', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data da movimentação')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('origem', models.CharField(blank=True, max_length=50, verbose_name='Origem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('estornada', models.BooleanField(default=False, verbose_name='Estornada')),
                ('baixa_pagar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='financeiro.baixapagar', verbose_name='Baixa de origem')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='financeiro.categoriafinanceira', verbose_name='Categoria')),
                ('conta_financeira', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='financeiro.contafinanceira', verbose_name='Conta financeira')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_financeiras_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Movimentação financeira',
                'verbose_name_plural': 'Movimentações financeiras',
                'ordering': ['-data_movimentacao', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ParcelaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='Número da parcela')),
                ('data_vencimento', models.DateField(verbose_name='Data de vencimento')),
                ('valor_original', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor original')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor pago')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('parcial', 'Parcial'), ('paga', 'Paga'), ('cancelada', 'Cancelada')], default='pendente', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('conta_pagar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='financeiro.contapagar', verbose_name='Conta a pagar')),
            ],
            options={
                'verbose_name': 'Parcela a pagar',
                'verbose_name_plural': 'Parcelas a pagar',
                'ordering': ['data_vencimento', 'numero'],
            },
        ),
        migrations.AddField(
            model_name='baixapagar',
            name='parcela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='baixas', to='financeiro.parcelapagar', verbose_name='Parcela'),
        ),
        migrations.AddConstraint(
            model_name='contapagar',
            constraint=models.CheckConstraint(condition=models.Q(('valor_total__gt', 0)), name='financeiro_conta_pagar_valor_total_positivo'),
        ),
        migrations.AddConstraint(
            model_name='contapagar',
            constraint=models.CheckConstraint(condition=models.Q(('valor_pago__gte', 0)), name='financeiro_conta_pagar_valor_pago_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='contapagar',
            constraint=models.CheckConstraint(condition=models.Q(('valor_pago__lte', models.F('valor_total'))), name='financeiro_conta_pagar_pago_nao_supera_total'),
        ),
        migrations.AddIndex(
            model_name='historicocontapagar',
            index=models.Index(fields=['conta_pagar', '-criado_em'], name='fin_hist_conta_data_idx'),
        ),
        migrations.AddIndex(
            model_name='historicocontapagar',
            index=models.Index(fields=['tipo_evento'], name='fin_hist_evento_idx'),
        ),
        migrations.AddConstraint(
            model_name='movimentacaofinanceira',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='financeiro_movimentacao_valor_positivo'),
        ),
        migrations.AddConstraint(
            model_name='parcelapagar',
            constraint=models.UniqueConstraint(fields=('conta_pagar', 'numero'), name='financeiro_parcela_numero_unico_por_conta'),
        ),
        migrations.AddConstraint(
            model_name='parcelapagar',
            constraint=models.CheckConstraint(condition=models.Q(('valor_original__gt', 0)), name='financeiro_parcela_valor_original_positivo'),
        ),
        migrations.AddConstraint(
            model_name='parcelapagar',
            constraint=models.CheckConstraint(condition=models.Q(('valor_pago__gte', 0)), name='financeiro_parcela_valor_pago_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='parcelapagar',
            constraint=models.CheckConstraint(condition=models.Q(('valor_pago__lte', models.F('valor_original'))), name='financeiro_parcela_pago_nao_supera_original'),
        ),
        migrations.AddConstraint(
            model_name='baixapagar',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='financeiro_baixa_valor_positivo'),
        ),
        migrations.AddConstraint(
            model_name='baixapagar',
            constraint=models.CheckConstraint(condition=models.Q(('juros__gte', 0)), name='financeiro_baixa_juros_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='baixapagar',
            constraint=models.CheckConstraint(condition=models.Q(('multa__gte', 0)), name='financeiro_baixa_multa_nao_negativa'),
        ),
        migrations.AddConstraint(
            model_name='baixapagar',
            constraint=models.CheckConstraint(condition=models.Q(('desconto__gte', 0)), name='financeiro_baixa_desconto_nao_negativo'),
        ),
    ]
