# Generated by Django 6.0.6 on 2026-07-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contafinanceira',
            options={'ordering': ['-conta_padrao', 'nome'], 'verbose_name': 'Conta financeira', 'verbose_name_plural': 'Contas financeiras'},
        ),
        migrations.AddField(
            model_name='contafinanceira',
            name='conta_padrao',
            field=models.BooleanField(default=False, verbose_name='Conta padrão'),
        ),
        migrations.AddField(
            model_name='contafinanceira',
            name='identificador',
            field=models.CharField(blank=True, help_text='Chave Pix, código da carteira, terminal, apelido ou outro identificador.', max_length=150, verbose_name='Identificador'),
        ),
        migrations.AlterField(
            model_name='contafinanceira',
            name='tipo',
            field=models.CharField(choices=[('caixa', 'Caixa'), ('conta_corrente', 'Conta corrente'), ('conta_poupanca', 'Conta poupança'), ('carteira_digital', 'Carteira digital'), ('adquirente', 'Adquirente'), ('investimento', 'Investimento'), ('outra', 'Outra')], default='conta_corrente', max_length=30, verbose_name='Tipo'),
        ),
        migrations.AddConstraint(
            model_name='contafinanceira',
            constraint=models.UniqueConstraint(condition=models.Q(('conta_padrao', True)), fields=('conta_padrao',), name='financeiro_apenas_uma_conta_padrao'),
        ),
    ]
