# Generated by Django 6.0.6 on 2026-07-15 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_alter_contafinanceira_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contafinanceira',
            name='financeiro_apenas_uma_conta_padrao',
        ),
    ]
