# Generated by Django 6.0.6 on 2026-07-19 17:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('financeiro', '0003_remove_contafinanceira_financeiro_apenas_uma_conta_padrao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(editable=False, unique=True, verbose_name='Número')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('nome_devedor', models.CharField(blank=True, help_text='Identificação preservada do cliente ou devedor no momento da criação da conta.', max_length=200, verbose_name='Nome do devedor')),
                ('documento_devedor', models.CharField(blank=True, max_length=20, verbose_name='Documento do devedor')),
                ('origem', models.CharField(choices=[('manual', 'Lançamento manual'), ('venda', 'Venda'), ('outra', 'Outra origem')], default='manual', max_length=20, verbose_name='Origem')),
                ('origem_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Identificador da origem')),
                ('origem_descricao', models.CharField(blank=True, max_length=200, verbose_name='Descrição da origem')),
                ('data_emissao', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data de emissão')),
                ('data_competencia', models.DateField(blank=True, null=True, verbose_name='Data de competência')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor total')),
                ('valor_recebido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor recebido')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('parcial', 'Parcial'), ('recebida', 'Recebida'), ('cancelada', 'Cancelada')], default='pendente', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cancelado_em', models.DateTimeField(blank=True, null=True, verbose_name='Cancelado em')),
                ('motivo_cancelamento', models.TextField(blank=True, verbose_name='Motivo do cancelamento')),
                ('cancelado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_receber_canceladas', to=settings.AUTH_USER_MODEL, verbose_name='Cancelado por')),
                ('categoria', models.ForeignKey(limit_choices_to={'tipo': 'receita'}, on_delete=django.db.models.deletion.PROTECT, related_name='contas_receber', to='financeiro.categoriafinanceira', verbose_name='Categoria')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_receber', to='clientes.cliente', verbose_name='Cliente')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_receber_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Conta a receber',
                'verbose_name_plural': 'Contas a receber',
                'ordering': ['-data_emissao', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoContaReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('criacao', 'Criação'), ('edicao', 'Edição'), ('parcela_criada', 'Parcela criada'), ('parcela_editada', 'Parcela editada'), ('recebimento', 'Recebimento registrado'), ('estorno', 'Recebimento estornado'), ('cancelamento', 'Cancelamento'), ('reativacao', 'Reativação'), ('integracao_venda', 'Integração com venda'), ('outro', 'Outro')], max_length=30, verbose_name='Tipo de evento')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('dados', models.JSONField(blank=True, default=dict, verbose_name='Dados do evento')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('conta_receber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='financeiro.contareceber', verbose_name='Conta a receber')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historicos_contas_receber', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Histórico da conta a receber',
                'verbose_name_plural': 'Históricos das contas a receber',
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ParcelaReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='Número da parcela')),
                ('data_vencimento', models.DateField(verbose_name='Data de vencimento')),
                ('valor_original', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor original')),
                ('valor_recebido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor recebido')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('parcial', 'Parcial'), ('recebida', 'Recebida'), ('cancelada', 'Cancelada')], default='pendente', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('conta_receber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='financeiro.contareceber', verbose_name='Conta a receber')),
            ],
            options={
                'verbose_name': 'Parcela a receber',
                'verbose_name_plural': 'Parcelas a receber',
                'ordering': ['data_vencimento', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='RecebimentoConta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_recebimento', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data do recebimento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor principal')),
                ('juros', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Juros')),
                ('multa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Multa')),
                ('desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Desconto financeiro')),
                ('valor_movimentado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor movimentado')),
                ('forma_recebimento', models.CharField(choices=[('pix', 'Pix'), ('dinheiro', 'Dinheiro'), ('cartao_debito', 'Cartão de débito'), ('cartao_credito', 'Cartão de crédito'), ('boleto', 'Boleto'), ('transferencia', 'Transferência'), ('cheque', 'Cheque'), ('outra', 'Outra')], default='pix', max_length=30, verbose_name='Forma de recebimento')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('registrado_em', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('estornado', models.BooleanField(default=False, verbose_name='Estornado')),
                ('estornado_em', models.DateTimeField(blank=True, null=True, verbose_name='Estornado em')),
                ('motivo_estorno', models.TextField(blank=True, verbose_name='Motivo do estorno')),
                ('conta_financeira', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recebimentos', to='financeiro.contafinanceira', verbose_name='Conta financeira')),
                ('estornado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recebimentos_conta_estornados', to=settings.AUTH_USER_MODEL, verbose_name='Estornado por')),
                ('parcela', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recebimentos', to='financeiro.parcelareceber', verbose_name='Parcela')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recebimentos_conta_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Recebimento de conta',
                'verbose_name_plural': 'Recebimentos de contas',
                'ordering': ['-data_recebimento', '-registrado_em'],
            },
        ),
        migrations.AddField(
            model_name='movimentacaofinanceira',
            name='recebimento_conta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='financeiro.recebimentoconta', verbose_name='Recebimento de origem'),
        ),
        migrations.AddConstraint(
            model_name='movimentacaofinanceira',
            constraint=models.CheckConstraint(condition=models.Q(('baixa_pagar__isnull', True), ('recebimento_conta__isnull', True), _connector='OR'), name='financeiro_movimentacao_uma_origem'),
        ),
        migrations.AddIndex(
            model_name='contareceber',
            index=models.Index(fields=['status', 'data_emissao'], name='fin_crec_status_emissao_idx'),
        ),
        migrations.AddIndex(
            model_name='contareceber',
            index=models.Index(fields=['origem', 'origem_id'], name='fin_creceber_origem_idx'),
        ),
        migrations.AddConstraint(
            model_name='contareceber',
            constraint=models.CheckConstraint(condition=models.Q(('valor_total__gt', 0)), name='financeiro_conta_receber_total_positivo'),
        ),
        migrations.AddConstraint(
            model_name='contareceber',
            constraint=models.CheckConstraint(condition=models.Q(('valor_recebido__gte', 0)), name='financeiro_conta_receber_recebido_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='contareceber',
            constraint=models.CheckConstraint(condition=models.Q(('valor_recebido__lte', models.F('valor_total'))), name='financeiro_conta_receber_recebido_ate_total'),
        ),
        migrations.AddIndex(
            model_name='historicocontareceber',
            index=models.Index(fields=['conta_receber', '-criado_em'], name='fin_hist_creceber_data_idx'),
        ),
        migrations.AddIndex(
            model_name='historicocontareceber',
            index=models.Index(fields=['tipo_evento'], name='fin_hist_creceber_evento_idx'),
        ),
        migrations.AddIndex(
            model_name='parcelareceber',
            index=models.Index(fields=['status', 'data_vencimento'], name='fin_preceber_status_venc_idx'),
        ),
        migrations.AddConstraint(
            model_name='parcelareceber',
            constraint=models.UniqueConstraint(fields=('conta_receber', 'numero'), name='financeiro_parcela_receber_numero_unico'),
        ),
        migrations.AddConstraint(
            model_name='parcelareceber',
            constraint=models.CheckConstraint(condition=models.Q(('valor_original__gt', 0)), name='financeiro_parcela_receber_valor_positivo'),
        ),
        migrations.AddConstraint(
            model_name='parcelareceber',
            constraint=models.CheckConstraint(condition=models.Q(('valor_recebido__gte', 0)), name='financeiro_parcela_receber_valor_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='parcelareceber',
            constraint=models.CheckConstraint(condition=models.Q(('valor_recebido__lte', models.F('valor_original'))), name='financeiro_parcela_receber_ate_original'),
        ),
        migrations.AddConstraint(
            model_name='recebimentoconta',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='financeiro_recebimento_valor_positivo'),
        ),
        migrations.AddConstraint(
            model_name='recebimentoconta',
            constraint=models.CheckConstraint(condition=models.Q(('juros__gte', 0)), name='financeiro_recebimento_juros_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='recebimentoconta',
            constraint=models.CheckConstraint(condition=models.Q(('multa__gte', 0)), name='financeiro_recebimento_multa_nao_negativa'),
        ),
        migrations.AddConstraint(
            model_name='recebimentoconta',
            constraint=models.CheckConstraint(condition=models.Q(('desconto__gte', 0)), name='financeiro_recebimento_desconto_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='recebimentoconta',
            constraint=models.CheckConstraint(condition=models.Q(('valor_movimentado__gte', 0)), name='financeiro_recebimento_movimentado_nao_negativo'),
        ),
    ]
