# Generated by Django 6.0.6 on 2026-08-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_contareceber_historicocontareceber_parcelareceber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contafinanceira',
            name='operacao',
            field=models.CharField(choices=[('distribuidora', 'Helvi Distribuidora'), ('use-helvi', 'Use Helvi')], db_index=True, default='distribuidora', max_length=20, verbose_name='Empresa/operação'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='operacao',
            field=models.CharField(choices=[('distribuidora', 'Helvi Distribuidora'), ('use-helvi', 'Use Helvi')], db_index=True, default='distribuidora', max_length=20, verbose_name='Empresa/operação'),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='operacao',
            field=models.CharField(choices=[('distribuidora', 'Helvi Distribuidora'), ('use-helvi', 'Use Helvi')], db_index=True, default='distribuidora', max_length=20, verbose_name='Empresa/operação'),
        ),
        migrations.AddField(
            model_name='movimentacaofinanceira',
            name='operacao',
            field=models.CharField(choices=[('distribuidora', 'Helvi Distribuidora'), ('use-helvi', 'Use Helvi')], db_index=True, default='distribuidora', max_length=20, verbose_name='Empresa/operação'),
        ),
    ]
