# Generated by Django 6.0.6 on 2026-07-05 19:14

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0003_alter_produto_foto_imagemproduto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(editable=False, unique=True, verbose_name='Número da compra')),
                ('fornecedor_nome', models.CharField(max_length=150, verbose_name='Fornecedor')),
                ('fornecedor_documento', models.CharField(blank=True, max_length=20, verbose_name='CPF/CNPJ')),
                ('fornecedor_telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('data_compra', models.DateField(verbose_name='Data da compra')),
                ('previsao_entrega', models.DateField(blank=True, null=True, verbose_name='Previsão de entrega')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('em_aberto', 'Em aberto'), ('aguardando_entrega', 'Aguardando entrega'), ('recebida', 'Recebida'), ('cancelada', 'Cancelada')], default='rascunho', max_length=30, verbose_name='Status')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Subtotal')),
                ('desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Desconto')),
                ('frete', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Frete')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('entrada_estoque_realizada', models.BooleanField(default=False, verbose_name='Entrada no estoque realizada')),
                ('financeiro_gerado', models.BooleanField(default=False, verbose_name='Financeiro gerado')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['-data_compra', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ItemCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade')),
                ('custo_unitario', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Custo unitário')),
                ('desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Desconto')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='compras.compra', verbose_name='Compra')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_compra', to='produtos.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Item da compra',
                'verbose_name_plural': 'Itens da compra',
                'ordering': ['id'],
            },
        ),
    ]
