# Generated by Django 6.0.6 on 2026-07-06 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='status_pagamento',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('parcial', 'Parcial'), ('pago', 'Pago')], default='pendente', max_length=20, verbose_name='Status do pagamento'),
        ),
    ]
