# Generated by Django 6.0.6 on 2026-07-07 02:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_compra_status_pagamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='recebida_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Recebida em'),
        ),
        migrations.AddField(
            model_name='compra',
            name='recebida_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_recebidas', to=settings.AUTH_USER_MODEL, verbose_name='Recebida por'),
        ),
        migrations.AddField(
            model_name='compra',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor pago'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('em_aberto', 'Em aberto'), ('aguardando_entrega', 'Aguardando entrega'), ('recebida', 'Recebida'), ('cancelada', 'Cancelada')], default='rascunho', max_length=30),
        ),
    ]
