# Generated by Django 6.0.6 on 2026-07-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_compra_recebida_em_compra_recebida_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='status',
            field=models.CharField(choices=[('em_aberto', 'Em aberto'), ('aguardando_entrega', 'Aguardando entrega'), ('recebida', 'Recebida'), ('cancelada', 'Cancelada')], default='aguardando_entrega', max_length=30),
        ),
    ]
