# Generated by Django 6.0.6 on 2026-07-08 02:12

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_alter_compra_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PagamentoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor pago')),
                ('forma_pagamento', models.CharField(choices=[('pix', 'Pix'), ('dinheiro', 'Dinheiro'), ('cartao', 'Cartão'), ('boleto', 'Boleto'), ('transferencia', 'Transferência'), ('outra', 'Outra')], default='pix', max_length=30, verbose_name='Forma de pagamento')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('registrado_em', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='compras.compra', verbose_name='Compra')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos_compras_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Pagamento da compra',
                'verbose_name_plural': 'Pagamentos da compra',
                'ordering': ['-registrado_em'],
            },
        ),
    ]
