# Generated by Django 6.0.6 on 2026-07-30 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_compra_fornecedor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='cancelada_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cancelada em'),
        ),
        migrations.AddField(
            model_name='compra',
            name='cancelada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_canceladas', to=settings.AUTH_USER_MODEL, verbose_name='Cancelada por'),
        ),
        migrations.AddField(
            model_name='compra',
            name='motivo_cancelamento',
            field=models.TextField(blank=True, verbose_name='Motivo do cancelamento'),
        ),
    ]
